var menuHeight=0;var bodyHeight=0;var bodyWidth=0;var headerHeight=0;var footerHeight=0;function scrollToHash(hash){headerHeight=$('header').height();console.log(headerHeight)
var sspeed=800;var docTop=$(hash).offset().top-headerHeight;$('html, body').animate({scrollTop:docTop},800,function(){$(".main-nav ul li a").removeClass("active");$(".main-nav ul li a").each(function(){if($(this).attr("href")==hash){$(this).addClass("active");}});});}
function checkPageLocation(){var locationHref=location.href;var locationOrigin=location.origin;if(location.hash!=""&&location.hash!='#home'&&location.hash!='#what-is-thermage'&&location.hash!='#results'&&location.hash!='#how-it-works'&&location.hash!='#faq'){location.href=location.protocol+"//"+location.host+'/'+404}else{if(location.hash=="#home"||location.hash=="#what-is-thermage"||location.hash=="#results"||location.hash=="#how-it-works"||location.hash=="#faq"){scrollToHash(location.hash);}}
if(location.pathname=='/find-a-doctor.html'){$('.main-nav .nav a[href="#home"]').removeClass('active')}}
window.onhashchange=function(){checkPageLocation();}
jQuery(document).ready(function(){checkPageLocation();if(jQuery('.product-logo').attr("src")!==undefined){var path=jQuery('.product-logo').attr("src");var fileNameIndex=path.lastIndexOf("/")+1;var siteDirectory=path.substr(0,fileNameIndex);}
var location=getLocation(window.location);$(".main-nav a").on('click',function(event){windowScrollActive=false;var sspeed=parseInt($(this).attr("data-speed"));$(".main-nav a").removeClass("active");$(".top-right-links a.active").removeClass("active");$(this).addClass("active");if(this.hash!==""){event.preventDefault();
var hash=this.hash;if(bodyWidth<=1000){hideMenu();}
$('html, body').animate({scrollTop:$(hash).offset().top-headerHeight},sspeed,function(){windowScrollActive=true;history.replaceState(undefined,undefined,hash);});}});var windowScrollActive=true;setTimeout(function(){var homeTop=$('#home').offset().top-headerHeight-100;var thermageTop=$('#what-is-thermage').offset().top-headerHeight-100;var resultsTop=$('#results').offset().top-headerHeight-100;var howItWorksTop=$('#how-it-works').offset().top-headerHeight-100;var faqTop=$('#faq').offset().top-headerHeight-100;if(location.pathname=="/"&&$(window).width()>1000){$(window).on('scroll',function(e){if(windowScrollActive&&!$('body').hasClass('dnnEditState')&&$(window).width()>1000){highlightMenuOnScroll($(window).scrollTop());}});}
function highlightMenuOnScroll(windowScrollPos){if(windowScrollPos>=homeTop&&windowScrollPos<(thermageTop)){if(!$('.main-nav ul.nav li:eq(1) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(1) a').addClass('active');history.replaceState(undefined,undefined,'#home');}}else if(windowScrollPos>=thermageTop&&windowScrollPos<(resultsTop)){if(!$('.main-nav ul.nav li:eq(2) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(2) a').addClass('active');history.replaceState(undefined,undefined,'#what-is-thermage');}}else if(windowScrollPos>=resultsTop&&windowScrollPos<(howItWorksTop)){if(!$('.main-nav ul.nav li:eq(3) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(3) a').addClass('active');history.replaceState(undefined,undefined,'#results');}}else if(windowScrollPos>=howItWorksTop&&windowScrollPos<(faqTop)){if(!$('.main-nav ul.nav li:eq(4) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(4) a').addClass('active');history.replaceState(undefined,undefined,'#how-it-works');}}else if(windowScrollPos>=faqTop&&windowScrollPos+$(window).height()<$(document).height()){if(!$('.main-nav ul.nav li:eq(5) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(5) a').addClass('active');history.replaceState(undefined,undefined,'#faq');}}else{return;}}},2000);$('.btn-isi').on('click',function(){$('#blurMe').addClass("blurMe");$("#isiContainer").modal({backdrop:'static',keyboard:false});});$('.btn-close-isi').on('click',function(){$('#blurMe').removeClass("blurMe");});$('.hamburger-menu').click(function(){if(jQuery('.hamburger-menu').find("i").hasClass("fa-bars")){openMenu();}
else{closeMenu();}});$("#beforeAfterCarousel").swiperight(function(){$(this).carousel('prev');});$("#beforeAfterCarousel").swipeleft(function(){$(this).carousel('next');});$("#thermageSystemCarousel").swiperight(function(){$(this).carousel('prev');});$("#thermageSystemCarousel").swipeleft(function(){$(this).carousel('next');});$(".products-nav ul").swipeleft(function(){var offsetNav=$(this).outerWidth()-bodyWidth;$(this).animate({'left':"-"+offsetNav+"px"},300,"linear",function(){});});$(".products-nav ul").swiperight(function(){$(this).animate({'left':"0px"},300,"linear",function(){});});setTimeout(function(){applyFluidResolution();},100);jQuery(window).resize(function(){applyFluidResolution();});function applyFluidResolution(){headerHeight=$('header').height();footerHeight=jQuery(".footer").outerHeight();jQuery("#contentPane").css("margin-top",headerHeight+"px");bodyHeight=jQuery("body").outerHeight();bodyWidth=jQuery("body").outerWidth();$('.features-bg').css("background-image","url("+siteDirectory+"service-history-lotus-bg-1344x992.png)");if(bodyWidth<=1100){$('.hero-image').attr("src",siteDirectory+"hero-model-image-mobile-1042x1000.png");$('.testimony-hero').attr("src",siteDirectory+"testimony-hero-modal-mobile-656x607.png");}
if(bodyWidth<=1000){$(".wrap-to-ul").wrapAll("<ul class='footer-wrapped-ul' />");$(".whats-in-icons h3").each(function(){$(this).html($(this).html().replace("<br>","<a></a>"));});menuHeight=jQuery(".top-right-links").outerHeight(true);}
else{$('.service-history-bg').css("background-image","none");$('.hero-image').attr("src",siteDirectory+"hero-model-image-1045x1228.png");$('.testimony-hero').attr("src",siteDirectory+"testimony-hero-modal-629x485.png");$(".whats-in-icons h3").each(function(){$(this).html($(this).html().replace("<a></a>","<br>"));});$(".footer-links").append($(".wrap-to-ul:first-child"));$(".footer-wrapped-ul").remove();$('.products-nav li.pro-menu:first-child a').parent().show();$(".top-right-links").attr("style","");}
$("div#contentPane").css("min-height",($(window).height()-(headerHeight+footerHeight))+"px");}
$('.top-right-links .mobile-menu-links a').on('click',function(){if(!$(this).hasClass('err-page-link')){if(!$(this).hasClass('mobile-contact-link')){event.preventDefault();closeMenu();var hash=$(this).attr('href');console.log($(hash).offset().top)
$('html, body').animate({scrollTop:$(hash).offset().top-headerHeight},800);}}})
var bodyScroll=$(window).scrollTop();function openMenu(){jQuery('.hamburger-menu').find("i").removeClass("fa-bars");jQuery('.hamburger-menu').find("i").addClass("fa-times");jQuery(".top-right-links").addClass('show');bodyScroll=$(window).scrollTop();$('body').addClass('show-menu');}
function closeMenu(){$('.top-right-links').scrollTop(0);jQuery('.hamburger-menu').find("i").addClass("fa-bars");jQuery('.hamburger-menu').find("i").removeClass("fa-times");jQuery(".top-right-links").removeClass('show');$('body').removeClass('show-menu');$(window).scrollTop(bodyScroll);}
function hideMenu(){$('.top-right-links').scrollTop(0);jQuery('.hamburger-menu').find("i").addClass("fa-bars");jQuery('.hamburger-menu').find("i").removeClass("fa-times");jQuery(".top-right-links").removeClass('show');$('body').removeClass('show-menu');$(window).scrollTop(bodyScroll);}
$("#faqAccordion").accordion();function getLocation(href){var location=document.createElement("a");location.href=href;if(location.host==""){location.href=location.href;}
return location;};});