var menuHeight=0;var bodyHeight=0;var bodyWidth=0;var headerHeight=0;function scrollToHash(hash){headerHeight=$('header').height();var sspeed=800;var docTop=$(hash).offset().top-headerHeight;if(hash=='#contact-a-representative'){docTop=$(document).height();}
$('html, body').animate({scrollTop:docTop},sspeed,function(){$(".main-nav ul li a").removeClass("active");$(".main-nav ul li a").each(function(){if($(this).attr("href")==hash){$(this).addClass("active");}else{if(hash=='#contact-a-representative'){$('.main-nav ul li:last a').addClass('active');}}});});}
function checkPageLocation(){var locationHref=location.href;var locationOrigin=location.origin;if(location.hash!=""&&location.hash!='#home'&&location.hash!='#the-thermage-system'&&location.hash!='#updates'&&location.hash!='#results'&&location.hash!='#why-thermage'&&location.hash!='#contact-a-representative'){location.href=location.protocol+"//"+location.host+'/hcp/'+404}else{if(location.hash=="#home"||location.hash=="#the-thermage-system"||location.hash=="#updates"||location.hash=="#results"||location.hash=="#why-thermage"||location.hash=="#contact-a-representative"){setTimeout(function(){scrollToHash(location.hash);},1000)}}}
window.onhashchange=function(){checkPageLocation();}
jQuery(document).ready(function(){checkPageLocation();if(jQuery('.product-logo').attr("src")!==undefined){var path=jQuery('.product-logo').attr("src");var fileNameIndex=path.lastIndexOf("/")+1;var siteDirectory=path.substr(0,fileNameIndex);}
var headerTopExtra=0;if($(window).width()>1000){headerTopExtra=164;}else if($(window).width()<1000){headerTopExtra=-37;}
$(".main-nav a").on('click',function(event){if(!$(this).hasClass('err-page')){var totalLi=$('.main-nav li').length-1;if($(this).parent().index()==totalLi){return;}
windowScrollActive=false;var sspeed=parseInt($(this).attr("data-speed"));$(".main-nav a").removeClass("active");$(this).addClass("active");if(this.hash!==""){event.preventDefault();var hash=this.hash;if(bodyWidth<=1000){hideMenu();}
$('html, body').animate({scrollTop:$(hash).offset().top-headerHeight},sspeed,function(){windowScrollActive=true;window.history.replaceState(null,null,hash);});}}});var windowScrollActive=true;setTimeout(function(){var homeTop=$('#home').offset().top-headerHeight-0;var thermageTop=$('#the-thermage-system').offset().top-headerHeight-200;var updatesTop=$('#updates').offset().top-headerHeight-200;var resultsTop=$('#results').offset().top-headerHeight-200;var whyThermageTop=$('#why-thermage').offset().top-headerHeight-200;var contactARepresentative=$('#contact-a-representative').offset().top-headerHeight-200;$(window).on('scroll',function(e){if(!$('#contact-a-representative .modal').is(':visible')){if(windowScrollActive&&!$('body').hasClass('dnnEditState')){highlightMenuOnScroll($(window).scrollTop());}}});function highlightMenuOnScroll(windowScrollPos){if(windowScrollPos>=homeTop&&windowScrollPos<(thermageTop)){if(!$('.main-nav ul.nav li:eq(1) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(1) a').addClass('active');history.replaceState(undefined,undefined,'#home');}}else if(windowScrollPos>=thermageTop&&windowScrollPos<(updatesTop)){if(!$('.main-nav ul.nav li:eq(2) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(2) a').addClass('active');history.replaceState(undefined,undefined,'#the-thermage-system');}}else if(windowScrollPos>=updatesTop&&windowScrollPos<(resultsTop)){if(!$('.main-nav ul.nav li:eq(3) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(3) a').addClass('active');history.replaceState(undefined,undefined,'#updates');}}else if(windowScrollPos>=resultsTop&&windowScrollPos<(whyThermageTop)){if(!$('.main-nav ul.nav li:eq(4) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(4) a').addClass('active');history.replaceState(undefined,undefined,'#results');}}else if(windowScrollPos>=whyThermageTop&&windowScrollPos+$(window).height()<$(document).height()){if(!$('.main-nav ul.nav li:eq(5) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(5) a').addClass('active');history.replaceState(undefined,undefined,'#why-thermage');}}else if(windowScrollPos>($(document).height()-($(window).height()+100))){if(!$('.main-nav ul.nav li:eq(6) a').hasClass('active')){$('.main-nav ul.nav li a').removeClass('active');$('.main-nav ul.nav li:eq(6) a').addClass('active');history.replaceState(undefined,undefined,'#contact-a-representative');}}}},2000)
var formOpenAction=$('.btn-contact-representative').last().attr('href');$('.btn-contact-representative').first().attr('href',formOpenAction);$('.mobile-contact-link').first().attr('href',formOpenAction);$('.products-nav .nav-item.pro-menu a.active').on('click',function(){$('.main-nav ul.nav li:eq(1) a').click();})
$('.btn-isi').on('click',function(e){e.stopPropagation();if($(this).parents('.menu-isi-links').length>0){closeMenu();}
$('#blurMe').addClass("blurMe");$("#isiContainer").modal({backdrop:'static',keyboard:false});});$('.btn-close-isi').on('click',function(){$('body').removeClass('show-menu');$('#blurMe').removeClass("blurMe");});$('body').on('click','.reload-window',function(){$(window).scrollTop(0);location.reload();})
$('body').on('click','.btn-contact-representative',function(){$('body').css('overflow','hidden');setTimeout(function(){$('.modal-mobile-header').show();},1000);});$('body').on('click','.mobile-contact-link',function(){$('body').css('overflow','hidden');setTimeout(function(){$('.modal-mobile-header').show();},1000);});$('body').on('click','.modal-mobile-header .mobile-close.reload',function(){$(window).scrollTop(0);history.replaceState(undefined,undefined,'#home');location.reload();$('.modal-mobile-header').hide();$('.modal').modal('hide');});$('body').on('click','#contact-a-representative button',function(){function myFunction(){if($('#contact-a-representative .submit-confirm').is(':visible')){$('.modal-mobile-header .mobile-close').hide();var maxId=setTimeout(function(){},0);for(var i=0;i<maxId;i+=1){clearTimeout(i);}}}
setInterval(myFunction,500);});$('.hamburger-menu').click(function(){if(jQuery('.hamburger-menu').find("i").hasClass("fa-bars")){openMenu();}
else{closeMenu();}});$("#beforeAfterCarousel").swiperight(function(){$(this).carousel('prev');});$("#beforeAfterCarousel").swipeleft(function(){$(this).carousel('next');});$("#thermageSystemCarousel").swiperight(function(){$(this).carousel('prev');});$("#thermageSystemCarousel").swipeleft(function(){$(this).carousel('next');});$(".products-nav ul").swipeleft(function(){var offsetNav=$(this).outerWidth()-bodyWidth;$(this).animate({'left':"-"+offsetNav+"px"},300,"linear",function(){});});$(".products-nav ul").swiperight(function(){$(this).animate({'left':"-20px"},300,"linear",function(){});});setTimeout(function(){applyFluidResolution();},1000);jQuery(window).resize(function(){applyFluidResolution();if($(window).width<=1000){$('#thermageSystemCarousel').carousel();}});if($(window).width()<=1023){convertToCarousel();}
$('.features-bg').css("background-image","url("+siteDirectory+"bg-1000x1272-features.png)");function applyFluidResolution(){headerHeight=$('header').height();bodyWidth=jQuery("body").outerWidth();if(bodyWidth<=1100){$('.hero-image').attr("src",siteDirectory+"mobile-photo-547x800-thermage-flex-system.png");$('.service-history-bg').css("background-image","url("+siteDirectory+"mobile-bg-1081x768-lotus.png)");$('.features-bg').css("background-image","url("+siteDirectory+"mobile-bg-1000x522-features.png)");}else{$('.hero-image').attr("src",siteDirectory+"photo-1596x1220-thermage-flex-system.png");$('.service-history-bg').css("background-image","url("+siteDirectory+"bg-992x1344-lotus.png)");$('.features-bg').css("background-image","url("+siteDirectory+"bg-1000x1272-features.png)");}
if(bodyWidth<=1023){convertToCarousel();}}
function convertToCarousel(){$('#thermageSystemCarousel .carousel-inner .toggleAsSlide').each(function(){$('#thermageSystemCarousel .carousel-inner').append($(this).html());$(this).remove();});$('.thermage-system .rearrangeSection').each(function(){$(".thermage-system").prepend($(this));});var curSlide=0;$('#thermageSystemCarousel .col-6.call-to-action').each(function(){if(curSlide==0){$(this).addClass("active");}
curSlide++;$(this).addClass("carousel-item");$(this).removeClass("col-6");$(this).removeClass("call-to-action");});}
function recreateBannerSection(){$('.thermage-system .rearrangeSection').each(function(){$(".thermage-system").prepend($(this));});$(".pair1").wrapAll("<div class='row toggleAsSlide'>");$(".pair2").wrapAll("<div class='row toggleAsSlide'>");$('#thermageSystemCarousel .carousel-inner .carousel-item').each(function(){$(this).addClass("call-to-action");$(this).addClass("col-6");$(this).removeClass("carousel-item");});}
$('body').on('click','.mobile-menu-links a',function(){if(!$(this).hasClass('err-page-link')){if(!$(this).hasClass('mobile-contact-link')){event.preventDefault();closeMenu();var hash=$(this).attr('href');$('html, body').animate({scrollTop:$(hash).offset().top-headerHeight},800);}else{$('body').removeClass('show-menu');$('.top-right-links').show();}}});$('body .menu-isi-links').on('click','a',function(){closeMenu();})
var bodyScroll=$(window).scrollTop();function openMenu(){jQuery('.hamburger-menu').find("i").removeClass("fa-bars");jQuery('.hamburger-menu').find("i").addClass("fa-times");bodyScroll=$(window).scrollTop();$('body').addClass('show-menu');}
function closeMenu(){$('.top-right-links').scrollTop(0);jQuery('.hamburger-menu').find("i").addClass("fa-bars");jQuery('.hamburger-menu').find("i").removeClass("fa-times");$('body').removeClass('show-menu');$(window).scrollTop(bodyScroll);}
function hideMenu(){$('.top-right-links').scrollTop(0);jQuery('.hamburger-menu').find("i").addClass("fa-bars");jQuery('.hamburger-menu').find("i").removeClass("fa-times");$('body').removeClass('show-menu');$(window).scrollTop(bodyScroll);}});